name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: debian:bookworm

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install --yes \
            git \
            jq \
            jsonlint \
            make \
            moreutils
      - uses: actions/checkout@v6
      - name: Check JSON formatting
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          make check
      - name: Lint JSON
        run: find . -not -type d -name '*.json' | xargs -n1 -exec jsonlint-php
